name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debian:
    name: Debian Trixie
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    
    - name: Add Debian experiment repository
      run: echo "deb http://deb.debian.org/debian experimental main contrib non-free non-free-firmware" > /etc/apt/sources.list.d/experimental.list

    - name: Update repository
      run: apt-get update -y

    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++

    - name: Install build dependencies
      run: mk-build-deps -i -t "apt-get --yes" -r

    - name: Build Package
      run: dpkg-buildpackage -b -uc -us -j$(nproc)

