name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debian:
    name: Debian Trixie
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    
    - name: Add Debian experiment repository
      run: echo "deb http://deb.debian.org/debian experimental main contrib non-free non-free-firmware" > /etc/apt/sources.list.d/experimental.list

    - name: Update repository
      run: apt-get update -y

    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++

    - name: Install build dependencies
      run: mk-build-deps -i -t "apt-get --yes" -r

    - name: Build Package
      run: dpkg-buildpackage -b -uc -us -j$(nproc)

  python-package:
    name: Python Package Build 
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13' ]
        os: [ubuntu-latest, windows-latest, macos-latest]
        qt-version: ["6.7.*"]
        include:
          - os: ubuntu-latest
            qt-arch: 'linux_gcc_64'
          - os: windows-latest
            qt-arch: 'win64_msvc2019_64'
          - os: macos-latest
            qt-arch: 'clang_64'

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    
    - name: Setup Ninja
      uses: kobiton/action-setup-ninja@f2ba2a8c0a6564883bafc14bee416b154a85a659
      with:
        # ninja version to download. Default: 1.10.0
        version: 1.11.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Qt on ${{ matrix.os }}
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt-version }}
        target: 'desktop'
        arch: ${{ matrix.qt-arch }}
        dir: '${{ github.workspace }}/.install_qt/'
        install-deps: 'true'
        modules: 'qt5compat'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'false'
        set-env: 'true'
        tools-only: 'false'


    - name: Build Package
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        python setup.py sdist bdist_wheel

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.qt-version }}
        path: dist/*
        if-no-files-found: 'error'

    

